FROM ubuntu:latest

WORKDIR /app

COPY requirements.txt requirements.txt
RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get install -y --no-install-recommends \
    wkhtmltopdf 

COPY . .

CMD ["python3", "app.py"]