version: '3.9'

services:
  nginx:
    container_name: nginx
    ports:
      - '5000:80'
    build: ./nginx
    depends_on:
      - auth
      - admin

  admin:
    container_name: admin
    build: ./admin
    volumes:
      - ./admin:/app/src
      - ./shared:/app/shared
    env_file:
      - .env

  adminv2:
    container_name: adminv2
    build: ./adminv2
    volumes:
      - ./adminv2:/app/src
      - ./shared:/app/shared
    env_file:
      - .env

  auth:
    container_name: auth
    build: ./auth
    volumes:
      - ./auth:/app/src
      - ./shared:/app/shared
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis

  old:
    container_name: old
    build: ./old
    volumes:
      - ./old:/app/src
      - ./shared:/app/shared

    env_file:
      - .env

  customer:
    container_name: customer
    build: ./customer
    volumes:
      - ./customer:/app/src
      - ./shared:/app/shared
    env_file:
      - .env

  vendor:
    container_name: vendor
    build: ./vendor
    volumes:
      - ./vendor:/app/src
      - ./shared:/app/shared
    env_file:
      - .env
