version: '3.8'

services:
  nginx:
    ports:
      - '5000:80'
    build: ./nginx
    depends_on:
      - admin
      - customer
      - vendor
      # - invoice
      - old

  redis:
    image: redis

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.prod
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./shared:/shared
      - /app/node_modules

  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile.prod
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./shared:/shared
      - /app/node_modules

  vendor:
    build:
      context: ./vendor
      dockerfile: Dockerfile.prod
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./shared:/shared
      - /app/node_modules

  invoice:
    build:
      context: ./invoice
      dockerfile: Dockerfile.prod
    env_file:
      - .env

  old:
    build:
      context: ./old
      dockerfile: Dockerfile.prod
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - /app/node_modules
