version: '3.9'

services:
  nginx:
    container_name: nginx
    ports:
      - '5000:80'
    build: ./nginx
    depends_on:
      - customer
      - admin

  admin:
    container_name: admin
    build: ./admin
    volumes:
      - ./admin:/app/src
      - ./shared:/app/shared
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis

  customer:
    container_name: customer
    build: ./customer
    volumes:
      - ./customer:/app/src
      - ./shared:/app/shared
    env_file:
      - .env

  vendor:
    container_name: vendor
    build: ./vendor
    volumes:
      - ./vendor:/app/src
      - ./shared:/app/shared
    env_file:
      - .env
