version: '3.9'

services:
  nginx:
    container_name: nginx
    ports:
      - '80:80'
      - '443:433'
    build: ./nginx
    depends_on:
      - auth
      - admin
    
  admin:
    container_name: admin
    build: ./admin
    volumes:
      - ./admin:/app/src
      - ./shared:/app/shared  
    env_file:
      - .env
 
  auth:
    container_name: auth
    build: ./auth
    volumes:
      - ./auth:/app/src
      - ./shared:/app/shared  
    env_file:
      - .env
  
  redis:
    container_name: redis
    image: redis

  # old:
  #   container_name: old
  #   build: ./old
  #   volumes:
  #     - ./old:/app/src
  #     - ./shared:/app/shared  

    env_file:
      - .env
